FROM jenkins/jenkins:lts-jdk11
# Install plugins
COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Set env vars.
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
ENV CASC_JENKINS_CONFIG="/var/jenkins_home/jcasc/jcasc.yaml"
ENV JENKINS_ADMIN_PASSWORD="admin"

# Install config
COPY --chown=jenkins:jenkins ./jcasc /var/jenkins_home/jcasc
