jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Agent/Build:admin"
      - "Agent/Configure:admin"
      - "Agent/Connect:admin"
      - "Agent/Create:admin"
      - "Agent/Delete:admin"
      - "Agent/Disconnect:admin"
      - "Credentials/Create:admin"
      - "Credentials/Delete:admin"
      - "Credentials/ManageDomains:admin"
      - "Credentials/Update:admin"
      - "Credentials/View:admin"
      - "Job/Build:admin"
      - "Job/Cancel:admin"
      - "Job/Configure:admin"
      - "Job/Create:admin"
      - "Job/Delete:admin"
      - "Job/Discover:admin"
      - "Job/Move:admin"
      - "Job/Read:admin"
      - "Job/Workspace:admin"
      - "Lockable Resources/Reserve:admin"
      - "Lockable Resources/Unlock:admin"
      - "Lockable Resources/View:admin"
      - "Overall/Administer:admin"
      - "Overall/Read:admin"
      - "Run/Delete:admin"
      - "Run/Replay:admin"
      - "Run/Update:admin"
      - "SCM/Tag:admin"
      - "View/Configure:admin"
      - "View/Create:admin"
      - "View/Delete:admin"
      - "View/Read:admin"
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "unix:///var/run/docker.sock"
        readTimeout: 60
      name: "docker"
      templates:
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jenkins/agent"
        labelString: "jenkins-agent"
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
        remoteFs: "/home/jenkins"
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "maven"
        labelString: "docker-maven"
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "docker-maven"
  - name: "jenkins-agent"
  - name: "master"
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        password: ${JENKINS_ADMIN_PASSWORD}
        properties:
        - "apiToken"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "admin@admin.com"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
    - script: >
        folder('DevOpsSchool') {
            displayName('DevOpsSchool')
            description('DevOpsSchool')
        }    

    - file: /var/jenkins_home/jcasc/jobs/simple-job.groovy
    - file: /var/jenkins_home/jcasc/jobs/pipeline-01.groovy
    - file: /var/jenkins_home/jcasc/jobs/generator.groovy
    - file: /var/jenkins_home/jcasc/jobs/piplene-ci-maven-ut.groovy
    - file: /var/jenkins_home/jcasc/jobs/pipeline-error.groovy
    - file: /var/jenkins_home/jcasc/jobs/pipeline-scm.groovy
    - file: /var/jenkins_home/jcasc/jobs/pipeline-parallel.groovy
    - file: /var/jenkins_home/jcasc/jobs/pipeline-multibranch.groovy
